// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCNk8b-YP_58XPjeuGnPbT_de-uMW1m64',
    appId: '1:764939435209:web:ac09fd89253420b83ea118',
    messagingSenderId: '764939435209',
    projectId: 'flutterfirebasereni',
    authDomain: 'flutterfirebasereni.firebaseapp.com',
    storageBucket: 'flutterfirebasereni.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1YzP9aOZz1mV_uz9eqSJB9cRi_2UofEA',
    appId: '1:764939435209:android:78c568ed8743574e3ea118',
    messagingSenderId: '764939435209',
    projectId: 'flutterfirebasereni',
    storageBucket: 'flutterfirebasereni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNyZ08IKv0myypRQxAHrF5_rTf-mei-Ns',
    appId: '1:764939435209:ios:e179e9414170d4e93ea118',
    messagingSenderId: '764939435209',
    projectId: 'flutterfirebasereni',
    storageBucket: 'flutterfirebasereni.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNyZ08IKv0myypRQxAHrF5_rTf-mei-Ns',
    appId: '1:764939435209:ios:e179e9414170d4e93ea118',
    messagingSenderId: '764939435209',
    projectId: 'flutterfirebasereni',
    storageBucket: 'flutterfirebasereni.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCNk8b-YP_58XPjeuGnPbT_de-uMW1m64',
    appId: '1:764939435209:web:3549fd85cea80ae23ea118',
    messagingSenderId: '764939435209',
    projectId: 'flutterfirebasereni',
    authDomain: 'flutterfirebasereni.firebaseapp.com',
    storageBucket: 'flutterfirebasereni.appspot.com',
  );

}