// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8dOYgwuNBGPZfbKWqr3VArzV-Gck7M5s',
    appId: '1:378859756763:web:1bfa81c6c832dd3f4c40fe',
    messagingSenderId: '378859756763',
    projectId: 'notes-c0c65',
    authDomain: 'notes-c0c65.firebaseapp.com',
    storageBucket: 'notes-c0c65.appspot.com',
    measurementId: 'G-M8M5ZJBEZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDQqPlKaaKcoP7aUGZxjktVsjXZUP1uZk',
    appId: '1:378859756763:android:427c9da03dddeca54c40fe',
    messagingSenderId: '378859756763',
    projectId: 'notes-c0c65',
    storageBucket: 'notes-c0c65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0lc9b-RVjCTho-J_CHtERHgvnL8hAuGw',
    appId: '1:378859756763:ios:375142124483f0f94c40fe',
    messagingSenderId: '378859756763',
    projectId: 'notes-c0c65',
    storageBucket: 'notes-c0c65.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0lc9b-RVjCTho-J_CHtERHgvnL8hAuGw',
    appId: '1:378859756763:ios:375142124483f0f94c40fe',
    messagingSenderId: '378859756763',
    projectId: 'notes-c0c65',
    storageBucket: 'notes-c0c65.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8dOYgwuNBGPZfbKWqr3VArzV-Gck7M5s',
    appId: '1:378859756763:web:6ba325cc402af1564c40fe',
    messagingSenderId: '378859756763',
    projectId: 'notes-c0c65',
    authDomain: 'notes-c0c65.firebaseapp.com',
    storageBucket: 'notes-c0c65.appspot.com',
    measurementId: 'G-MR7CJYLN2P',
  );

}