// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwroGYPxEwXUg9AaIYK9IfiMNYfvBD9XM',
    appId: '1:953695291436:web:0a7b4475a84c328318a989',
    messagingSenderId: '953695291436',
    projectId: 'notes1-185df',
    authDomain: 'notes1-185df.firebaseapp.com',
    storageBucket: 'notes1-185df.appspot.com',
    measurementId: 'G-RKTG8N7GVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9N6Tr0n4n5Hp2FVLiL4lhmYtbjzRvUxQ',
    appId: '1:953695291436:android:d30ac2cab99a4a2318a989',
    messagingSenderId: '953695291436',
    projectId: 'notes1-185df',
    storageBucket: 'notes1-185df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKm-i4dEM60Bj90oLGBuz0sWuN8S14aFc',
    appId: '1:953695291436:ios:f15f6b2f27d3b55d18a989',
    messagingSenderId: '953695291436',
    projectId: 'notes1-185df',
    storageBucket: 'notes1-185df.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKm-i4dEM60Bj90oLGBuz0sWuN8S14aFc',
    appId: '1:953695291436:ios:f15f6b2f27d3b55d18a989',
    messagingSenderId: '953695291436',
    projectId: 'notes1-185df',
    storageBucket: 'notes1-185df.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwroGYPxEwXUg9AaIYK9IfiMNYfvBD9XM',
    appId: '1:953695291436:web:b6c73d4d74c6a53618a989',
    messagingSenderId: '953695291436',
    projectId: 'notes1-185df',
    authDomain: 'notes1-185df.firebaseapp.com',
    storageBucket: 'notes1-185df.appspot.com',
    measurementId: 'G-0TB314N2FD',
  );
}
